In [39]:
import pandas as pd

df_leads = pd.read_csv("../data/raw/closed_deals.csv")
df_leads.head()

,mql_id,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue
0,5420aad7fec3549a85876ba1c529bd84,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0
1,a555fb36b9368110ede0f043dfc3b9a0,bbb7d7893a450660432ea6652310ebb7,09285259593c61296eef10c734121d5b,d3d1e91a157ea7f90548eef82f1955e3,2018-05-08 20:17:59,car_accessories,industry,eagle,NaN,NaN,NaN,reseller,NaN,0.0
2,327174d3648a2d047e8940d7d15204ca,612170e34b97004b3ba37eae81836b4c,b90f87164b5f8c2cfa5c8572834dbe3f,6565aa9ce3178a5caf6171827af3a9ba,2018-06-05 17:27:23,home_appliances,online_big,cat,NaN,NaN,NaN,reseller,NaN,0.0
3,f5fee8f7da74f4887f5bcae2bafb6dd6,21e1781e36faf92725dde4730a88ca0f,56bf83c4bb35763a51c2baab501b4c67,d3d1e91a157ea7f90548eef82f1955e3,2018-01-17 13:51:03,food_drink,online_small,NaN,NaN,NaN,NaN,reseller,NaN,0.0
4,ffe640179b554e295c167a2f6be528e0,ed8cb7b190ceb6067227478e48cf8dde,4b339f9567d060bcea4f5136b9f5949e,d3d1e91a157ea7f90548eef82f1955e3,2018-07-03 20:17:45,home_appliances,industry,wolf,NaN,NaN,NaN,manufacturer,NaN,0.0

In [40]:
# INVESTIGAR QUALIDADE DOS DADOS 
df_leads.info()

df_leads.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842 entries, 0 to 841
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   mql_id                         842 non-null    object
 1   seller_id                      842 non-null    object
 2   sdr_id                         842 non-null    object
 3   sr_id                          842 non-null    object
 4   won_date                       842 non-null    object
 5   business_segment               841 non-null    object
 6   lead_type                      836 non-null    object
 7   lead_behaviour_profile         665 non-null    object
 8   has_company                    63 non-null     object
 9   has_gtin                       64 non-null     object
 10  average_stock                  66 non-null     object
 11  business_type                  832 non-null    object
 12  declared_product_catalog_size  69 non-null     float64
 13  declared_monthly_revenue       842 non-null    float64
dtypes: float64(2), object(12)
memory usage: 92.2+ KB

mql_id                             0
seller_id                          0
sdr_id                             0
sr_id                              0
won_date                           0
business_segment                   1
lead_type                          6
lead_behaviour_profile           177
has_company                      779
has_gtin                         778
average_stock                    776
business_type                     10
declared_product_catalog_size    773
declared_monthly_revenue           0
dtype: int64

In [41]:
# VERIFICAR DUPLICATOS POR LINHAS

df_leads.duplicated().sum()

np.int64(0)

In [42]:
# TRATAR VALORES NULOS

# Colunas categóricas
colunas_categoricas = [
    'business_segment',
    'lead_type',
    'lead_behaviour_profile',
    'has_company',
    'has_gtin',
    'average_stock',
    'business_type'
]

for coluna in colunas_categoricas:
    df_leads[coluna] = df_leads[coluna].fillna('Não informado')

# Coluna numérica
mediana_catalogo = df_leads['declared_product_catalog_size'].median()

df_leads['declared_product_catalog_size'] = (
    df_leads['declared_product_catalog_size'].fillna(mediana_catalogo)
)

#VALIDAR NULOS TRATADOS

df_leads.isnull().sum()

mql_id                           0
seller_id                        0
sdr_id                           0
sr_id                            0
won_date                         0
business_segment                 0
lead_type                        0
lead_behaviour_profile           0
has_company                      0
has_gtin                         0
average_stock                    0
business_type                    0
declared_product_catalog_size    0
declared_monthly_revenue         0
dtype: int64

In [43]:
# CONVERTER WON_DATE PARA DATA

df_leads['won_date'] = pd.to_datetime(df_leads['won_date']).dt.date

df_leads.head(10)

,mql_id,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue
0,5420aad7fec3549a85876ba1c529bd84,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26,pet,online_medium,cat,Não informado,Não informado,Não informado,reseller,100.0,0.0
1,a555fb36b9368110ede0f043dfc3b9a0,bbb7d7893a450660432ea6652310ebb7,09285259593c61296eef10c734121d5b,d3d1e91a157ea7f90548eef82f1955e3,2018-05-08,car_accessories,industry,eagle,Não informado,Não informado,Não informado,reseller,100.0,0.0
2,327174d3648a2d047e8940d7d15204ca,612170e34b97004b3ba37eae81836b4c,b90f87164b5f8c2cfa5c8572834dbe3f,6565aa9ce3178a5caf6171827af3a9ba,2018-06-05,home_appliances,online_big,cat,Não informado,Não informado,Não informado,reseller,100.0,0.0
3,f5fee8f7da74f4887f5bcae2bafb6dd6,21e1781e36faf92725dde4730a88ca0f,56bf83c4bb35763a51c2baab501b4c67,d3d1e91a157ea7f90548eef82f1955e3,2018-01-17,food_drink,online_small,Não informado,Não informado,Não informado,Não informado,reseller,100.0,0.0
4,ffe640179b554e295c167a2f6be528e0,ed8cb7b190ceb6067227478e48cf8dde,4b339f9567d060bcea4f5136b9f5949e,d3d1e91a157ea7f90548eef82f1955e3,2018-07-03,home_appliances,industry,wolf,Não informado,Não informado,Não informado,manufacturer,100.0,0.0
5,b94fba7670eeb44dce2a0d8eb790e9f5,1c742ac33582852aaf3bcfbf5893abcf,fdb16d3cbbeb5798f2f66c4096be026d,495d4e95a8cf8bbf8b432b612a2aa328,2018-02-07,health_beauty,online_medium,Não informado,Não informado,Não informado,Não informado,manufacturer,100.0,0.0
6,c3e30ed7ac989117c7e1e719b4ac128f,92d7568ad0c5c76fd7d341b2d46f24d6,4b339f9567d060bcea4f5136b9f5949e,85fc447d336637ba1df43e793199fbc8,2018-04-16,computers,online_medium,wolf,Não informado,Não informado,Não informado,reseller,100.0,0.0
7,b02c89251106e1fdd9d92744be9f94f2,44ed138eca6214d572ce1d813fb0049b,34d40cdaf94010a1d05b0d6212f9e909,4ef15afb4b2723d8f3d81e51ec7afefe,2018-04-17,health_beauty,offline,cat,Não informado,Não informado,Não informado,manufacturer,100.0,0.0
8,a90a37898cc5f2718385a2fb981caaff,0b28859cd04d23edefee9c591fb03cd8,f42a2bd194f7802ab052a815c8de65b7,6565aa9ce3178a5caf6171827af3a9ba,2018-05-14,household_utilities,offline,eagle,Não informado,Não informado,Não informado,reseller,100.0,0.0
9,0173e8d8b1d94a355b440fb67388f532,87d73636a3acf123e842bb890a4db036,9d12ef1a7eca3ec58c545c678af7869c,9e4d1098a3b0f5da39b0bc48f9876645,2018-04-24,household_utilities,online_medium,eagle,Não informado,Não informado,Não informado,manufacturer,100.0,0.0

In [44]:
#EXPORTACAO DOS DADOS TRATADOS PARA A CAMADA SILVER


df_leads.to_csv(
    "../data/silver/closed_deals_clean.csv",
    index=False
)